### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by mattlaguardia** [skuebna/c-data-structures#1]
How do i test the output?

**Comment by skuebna** [comment]
**I'll update README file**
I hope to soon upload an explanation document also.

**create a text file (on Windows machine for now), then close it**
 75
  80
  90
  10
  30
  40
  77



**compile it, create an executable**
g++ avl.cpp -o avl

**run the executable**
 ./avl

**review output**
```
EXAMPLE OF FINAL OUTPUT
         	       75
                    /      \
                 30   	    80
	      /	   \	  /	\
	   10	   40   77	90
```

**Comment by skuebna** [comment]
Let me know if that works for you.
